# Generated by Django 5.1 on 2025-01-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='email',
            field=models.CharField(default='example@example.com', max_length=100),
        ),
    ]
