# Generated by Django 5.1 on 2025-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_coffee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='coffee_type',
            field=models.CharField(choices=[('indian', 'Indian'), ('russian', 'Russian'), ('american', 'American')], default='indian', max_length=20),
        ),
        migrations.AddField(
            model_name='coffee',
            name='number_of_cups',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
