# Generated by Django 5.1 on 2025-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_coffee_coffee_type_coffee_number_of_cups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='coffee_type',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='number_of_cups',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
