# Generated by Django 5.1 on 2025-01-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_coffee_coffee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='coffee_type',
            field=models.CharField(default='Indian', max_length=100),
        ),
        migrations.AddField(
            model_name='coffee',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
